/**
 * Jorge Electricidad — shared site content.
 * All copy is verbatim from the original business brief.
 */

export const BUSINESS = {
  name: "Jorge Electricidad",
  tagline: "Electricidad y Afines",
  phoneDisplay: "094 588 012",
  phoneTel: "+59894588012",
  whatsapp: "https://wa.me/59894588012",
  whatsappPrefilled:
    "https://wa.me/59894588012?text=Hola%20Jorge%2C%20quiero%20consultar%20por%20un%20servicio",
  email: "jorgitoballero@gmail.com",
  location: "Maldonado, Punta del Este, Uruguay",
  web: "jorge-electricidad.net",
} as const;

/**
 * Navbar — first six are scroll anchors on the home page (scroll-spy targets).
 * The "Blog" entry is a separate Next.js route (/blog), not a scroll target.
 */
export const NAV_LINKS = [
  { label: "Inicio", href: "#inicio" },
  { label: "Servicios", href: "#servicios" },
  { label: "Sobre Mí", href: "#sobre-mi" },
  { label: "Clientes", href: "#clientes" },
  { label: "Contacto", href: "#contacto" },
  { label: "Trabajos", href: "#trabajos" },
] as const;

/** Separate Blog route link — rendered in navbar + footer, NOT a scroll spy. */
export const BLOG_NAV_LINK = { label: "Blog", href: "/blog" } as const;

export type ServiceItem = {
  id: string;
  icon: "zap" | "circuit" | "cctv";
  title: string;
  description: string;
  items: string[];
};

export const SERVICES: ServiceItem[] = [
  {
    id: "electricidad",
    icon: "zap",
    title: "Electricidad",
    description:
      "Obra nueva, urgencias, instalaciones en general, motores, bombas, calefones, luminaria, automatismos.",
    items: [
      "Obra nueva",
      "Urgencias",
      "Instalaciones en general",
      "Motores y bombas",
      "Calefones",
      "Luminaria",
      "Automatismos",
    ],
  },
  {
    id: "afines",
    icon: "circuit",
    title: "Afines",
    description:
      "Portones eléctricos, domótica, control de accesos en edificios, video porteros, cableado de Internet y telefonía.",
    items: [
      "Portones eléctricos",
      "Domótica",
      "Control de accesos en edificios",
      "Video porteros",
      "Cableado de Internet",
      "Telefonía",
    ],
  },
  {
    id: "vigilancia",
    icon: "cctv",
    title: "Sistemas de Vigilancia",
    description:
      "Soluciones CCTV, Wifi, cámaras cableadas con DVR o wifi con NVR, cámaras con seguimiento, alarmas con aviso al teléfono.",
    items: [
      "CCTV",
      "Wifi",
      "Cámaras cableadas con DVR",
      "Cámaras wifi con NVR",
      "Cámaras con seguimiento",
      "Alarmas con aviso al teléfono",
    ],
  },
];

export const ABOUT_BIO =
  "Me llamo Jorge, nativo de Maldonado, con más de 5 años de experiencia brindando servicios en electricidad y afines de forma autónoma o trabajando para empresas, con formación en electrotecnia en UTU y bachiller en ingeniería. Estoy a sus órdenes, no dude en contactarse.";

export const ABOUT_HIGHLIGHTS = [
  { label: "+5 años experiencia", icon: "calendar" as const },
  { label: "Formación UTU", icon: "graduation" as const },
  { label: "Trabajos con firma UTE", icon: "badge" as const },
  { label: "Maldonado · Punta del Este", icon: "map" as const },
];

export const HERO_TRUST = [
  { label: "+5 años de experiencia", icon: "calendar" as const },
  { label: "Trabajos con firma UTE", icon: "badge" as const },
  { label: "Maldonado · Punta del Este", icon: "map" as const },
];

/**
 * Gallery categories — kept as display labels for the UI filter.
 * Firebase stores the slug (`filter-*`) as the `category` field; we convert
 * at the data layer so the rest of the app works with human-readable labels.
 */
export type GalleryCategory =
  | "Todas"
  | "Luminarias"
  | "Afines"
  | "Firma UTE"
  | "Cámaras";

export const GALLERY_FILTERS: GalleryCategory[] = [
  "Todas",
  "Luminarias",
  "Afines",
  "Firma UTE",
  "Cámaras",
];

/** Firebase category slugs (stored in Firestore). */
export const CATEGORY_SLUGS = {
  Luminarias: "filter-luminarias",
  Afines: "filter-afines",
  "Firma UTE": "filter-firma-ute",
  Cámaras: "filter-camaras-seguridad",
} as const;

/** Reverse map: slug → display label. */
export const SLUG_TO_CATEGORY: Record<string, GalleryCategory> = Object.fromEntries(
  Object.entries(CATEGORY_SLUGS).map(([label, slug]) => [slug, label as GalleryCategory])
);

/** All slugs (used by zod enum in the API). */
export const CATEGORY_SLUG_LIST = Object.values(CATEGORY_SLUGS);

export type GalleryItem = {
  id: string;
  /** Image URL — for Firebase items this is the CDN URL; for sample items, a local /images path. */
  imageUrl: string;
  /** Display label (Luminarias, Afines, Firma UTE, Cámaras). */
  category: Exclude<GalleryCategory, "Todas">;
  /** Alt text / caption. */
  altText: string;
  /** Optional description for the lightbox. */
  description?: string;
};

/**
 * Sample / fallback photos shown when Firebase isn't configured
 * or the API call fails. Uses local images bundled in /public.
 */
export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "panel",
    imageUrl: "/images/gallery-panel.png",
    altText: "Tablero eléctrico",
    category: "Firma UTE",
    description:
      "Armado y cableado de tablero principal con protecciones diferencial y térmicas, conforme a normativa UTE.",
  },
  {
    id: "cameras",
    imageUrl: "/images/gallery-cameras.png",
    altText: "Instalación CCTV",
    category: "Cámaras",
    description:
      "Sistema de cámaras cableadas con DVR y configuración de acceso remoto desde el teléfono.",
  },
  {
    id: "lighting",
    imageUrl: "/images/gallery-lighting.png",
    altText: "Iluminación LED",
    category: "Luminarias",
    description:
      "Renovación de luminaria a LED de bajo consumo con diseño de circuitos por ambiente.",
  },
  {
    id: "domotics",
    imageUrl: "/images/gallery-domotics.png",
    altText: "Domótica",
    category: "Afines",
    description:
      "Panel de control domótico para iluminación, climatización y seguridad integrada.",
  },
  {
    id: "gate",
    imageUrl: "/images/gallery-gate.png",
    altText: "Portón eléctrico",
    category: "Afines",
    description:
      "Instalación de motor para portón corredizo con control remoto y sistema de seguridad.",
  },
  {
    id: "intercom",
    imageUrl: "/images/gallery-intercom.png",
    altText: "Video portero",
    category: "Afines",
    description:
      "Video portero digital para edificio con control de accesos y conexión a telefonía interna.",
  },
];

export type Testimonial = {
  id: string;
  name: string;
  initials: string;
  quote: string;
};

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "gabriela",
    name: "Gabriela Segovia",
    initials: "GS",
    quote: "Excelente servicio !!",
  },
  {
    id: "norma",
    name: "Norma Nunez",
    initials: "NN",
    quote:
      "Excelente, atención muy conforme con el trabajo realizado, muy recomendable",
  },
  {
    id: "rossi",
    name: "Jorge Rossi",
    initials: "JR",
    quote: "Muy contento con el trabajo. Super profesional. Recomiendo",
  },
  {
    id: "sobredo",
    name: "Gabriel Sobredo",
    initials: "GS",
    quote: "Jorge un fenómeno, me solucionó un problemón!!!",
  },
  {
    id: "brusoni",
    name: "Gerardo Francisco Brusoni",
    initials: "GB",
    quote: "Muy buen trabajo, recomendable.",
  },
  {
    id: "pintos",
    name: "Rafael Pintos",
    initials: "RP",
    quote: "Muy buen trabajo, recomendable.",
  },
];

export const TESTIMONIALS_INTRO =
  "atender al cliente en su hogar puede llegar a ser un desafió para uno como  para el cliente, más allá de eso, creo que he tenido suerte con los clientes que me han tocado";

export type BlogPost = {
  id: string;
  title: string;
  date: string;
  excerpt: string;
  body: string[];
  featured?: boolean;
};

export const BLOG_POSTS: BlogPost[] = [
  {
    "id": "cargadores-auto-electrico-uruguay-2026",
    "title": "Instalar un cargador de auto eléctrico en casa en Uruguay (Guía 2026)",
    "date": "06/07/2026",
    "excerpt": "Guía técnica sobre los requisitos, trámites ante UTE, potencia contratada y medidas de seguridad necesarias para instalar un cargador de vehículo eléctrico en tu hogar.",
    "body": [
      "# Guía técnica: ¿Qué se necesita para instalar un cargador de auto eléctrico en casa?",
      "La llegada de un vehículo eléctrico al hogar es un hito emocionante, pero suele venir acompañado de una gran interrogante: **¿cómo adaptamos la instalación eléctrica de casa para cargarlo de forma segura?**",
      "Instalar un cargador doméstico (conocido técnicamente como *Wallbox* o SAVE) no es simplemente colgar un equipo en la pared y conectarlo. Requiere un análisis previo de tu instalación actual y el cumplimiento estricto de las normativas de UTE para evitar sobrecargas, multas o riesgos eléctricos.",
      "A continuación, te detallamos los puntos clave que debes considerar y los diferentes escenarios con los que te puedes encontrar según el Reglamento de Baja Tensión de UTE.",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## 📌 Contenido",
      "- [Las 4 preguntas iniciales del proyecto](#las-4-preguntas-iniciales)\n- [El gran desafío: La potencia contratada y los escenarios de UTE](#el-gran-desafio-la-potencia-contratada-y-los-escenarios-de-ute)\n- [Caso 1: Potencia monofásica menor al máximo (Menos de 7 kW)](#caso-1-potencia-monofasica-menor-al-maximo)\n- [Caso 2: Ya cuentas con el máximo monofásico (7 kW) y necesitas más](#caso-2-ya-cuentas-con-el-maximo-monofasico-y-necesitas-mas)\n- [Caso 3: Ya cuentas con suministro Trifásico (230V / 400V)](#caso-3-ya-cuentas-con-suministro-trifasico)\n- [Ojo con el \"Punto de Medida\" (El entorno del contador)](#ojo-con-el-punto-de-medida)\n- [La alternativa premium: Solicitar un suministro exclusivo para el vehículo](#la-alternativa-premium-solicitar-un-suministro-exclusivo)\n- [Requisitos técnicos obligatorios de la línea del cargador](#requisitos-tecnicos-obligatorios-de-la-linea-del-cargador)\n- [Conclusión](#conclusion)",
      "---",
      "<a id=\"las-4-preguntas-iniciales\"></a>",
      "## Las 4 preguntas iniciales del proyecto",
      "Para dimensionar correctamente la instalación y calcular un presupuesto adecuado, todo técnico habilitado te pedirá definir estos cuatro aspectos:",
      "1. **¿Qué marca y modelo de vehículo eléctrico vas a recibir?** Esto determina el tipo de conector que requiere (por ejemplo, Tipo 2 o Schuko de uso doméstico) y la potencia máxima que el propio auto es capaz de admitir en corriente alterna.\n2. **¿En qué zona geográfica se encuentra la propiedad?** Las condiciones de las redes de distribución pueden variar.\n3. **¿Dónde tienes pensado instalar el cargador?** No es lo mismo un garaje cerrado que una cochera abierta expuesta a la intemperie (lo que exige protecciones con un grado de estanqueidad mínimo IPX4 contra proyecciones de agua). También influye la distancia en metros desde el tablero principal.\n4. **¿Cuál es la potencia contratada actual de tu hogar?** Este suele ser el principal cuello de botella de cualquier proyecto residencial.",
      "---",
      "### También te puede interesar",
      "- [Aumento de potencia eléctrica en UTE: qué tener en cuenta](/blog/post/aumento-de-potencia-ute/)\n- [Requisitos del punto de medida según normativa de UTE](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute)",
      "---",
      "<a id=\"el-gran-desafio-la-potencia-contratada-y-los-escenarios-de-ute\"></a>",
      "## El gran desafío: La potencia contratada y los escenarios de UTE",
      "Un cargador de vehículo eléctrico consume una cantidad de energía considerable de manera continua. Dependiendo de tu situación actual frente a UTE, te encontrarás en uno de los siguientes casos:",
      "---",
      "<a id=\"caso-1-potencia-monofasica-menor-al-maximo\"></a>",
      "### Caso 1: Potencia monofásica menor al máximo (Menos de 7 kW)",
      "Si tienes contratada una potencia baja (por ejemplo, 3.7 kW o 4.6 kW), al encender el cargador probablemente \"salte\" la llave general si tienes otros electrodomésticos funcionando en simultáneo.",
      "- **La solución:** Si la idea es realizar una **carga lenta**, puedes solicitar un aumento de potencia ante UTE hasta el límite monofásico de 7 kW.\n- **Ventaja:** Si el aumento no supera los 7 kW y la instalación interna está en condiciones, generalmente el trámite lo puede gestionar el propio usuario sin necesidad de contratar una firma instaladora autorizada. Solo requerirá la mano de obra para cablear la línea exclusiva del cargador.\n- **Estrategia:** Deberás organizar la carga del auto para la madrugada, cuando el consumo de la casa es mínimo, evitando encender motores o sistemas de climatización grandes en esas horas.",
      "---",
      "<a id=\"caso-2-ya-cuentas-con-el-maximo-monofasico-y-necesitas-mas\"></a>",
      "### Caso 2: Ya cuentas con el máximo monofásico (7 kW) y necesitas más",
      "Por normativa de UTE, para evitar desequilibrios en la red pública, **no se permite instalar puntos de carga monofásicos de potencia superior a 7.4 kW**. Si requieres más potencia porque buscas una carga estándar o semirrápida, obligatoriamente debes pasar a un suministro trifásico.",
      "- **Trámite obligatorio:** Este cambio de categoría y aumento de potencia ya **no lo puede gestionar el usuario de forma particular**. Exige la intervención de una Firma Instaladora y un Técnico Autorizado por UTE que firme el trámite de Asunción de Responsabilidad (DAR).\n- **Costos asociados:** Implica modificar el cableado general de la propiedad desde el medidor exterior hasta tu tablero principal para adaptarlo a la nueva potencia. La normativa no contempla excepciones; si no se adecúa la instalación fija, UTE no otorgará el aumento.",
      "---",
      "<a id=\"caso-3-ya-cuentas-con-suministro-trifasico\"></a>",
      "### Caso 3: Ya cuentas con suministro Trifásico (230V / 400V)",
      "Es el escenario más amigable. En la mayoría de los casos, la potencia disponible en un sistema trifásico es suficiente para absorber el consumo de una estación de carga.",
      "- **Procedimiento:** El trabajo técnico se reduce a instalar la línea dedicada para el cargador y realizar un **balanceo de cargas** entre las tres fases en el tablero general para asegurar que el consumo de la casa y del auto quede distribuido de manera uniforme.",
      "---",
      "<a id=\"ojo-con-el-punto-de-medida\"></a>",
      "## Ojo con el \"Punto de Medida\" (El entorno del contador)",
      "Un detalle técnico y económico que muchos propietarios pasan por alto es el estado del nicho o lugar donde está el contador de UTE.",
      "Cada vez que se solicita una modificación de la instalación (como un paso a trifásica o un aumento grande de potencia), UTE envía inspectores a revisar el lugar. Si el medidor comparte padrón con otra vivienda sin una centralización adecuada, o si las cajas y cañerías del pilar están obsoletas, deterioradas o fuera de la normativa vigente, **el inspector rechazará la solicitud**.",
      "Modificar y poner a norma un punto de medida viejo puede elevar los costos del proyecto desde unos 200 USD en casos sencillos hasta superar los 1.000 USD si hay que reformar pilares de mampostería enteros.",
      "---",
      "<a id=\"la-alternativa-premium-solicitar-un-suministro-exclusivo\"></a>",
      "## La alternativa premium: Solicitar un suministro exclusivo para el vehículo",
      "Si no deseas tocar la instalación eléctrica actual de tu casa, cambiar tus tarifas residenciales, ni arriesgarte a tener que reformar tableros antiguos, la normativa de UTE contempla una excelente alternativa: **solicitar un segundo medidor independiente y exclusivo para la carga del vehículo eléctrico**.",
      "- **Cómo funciona:** Se gestiona ante UTE una nueva instalación de enlace independiente a la de la vivienda. Tendrás un contador para los consumos normales de tu hogar y otro contador dedicado únicamente a alimentar el circuito del cargador.\n- **Ventajas:** Facilita enormemente el control exacto de los gastos asociados al automóvil y te permite optar por tarifas horarias específicas para movilidad eléctrica sin interferir con las dinámicas de consumo de tu familia dentro de la casa. Al igual que los casos anteriores, requiere ser proyectado y ejecutado por un técnico electricista registrado.",
      "---",
      "<a id=\"requisitos-tecnicos-obligatorios-de-la-linea-del-cargador\"></a>",
      "## Requisitos técnicos obligatorios de la línea del cargador",
      "Independientemente del escenario en el que te encuentres, el Reglamento de UTE exige que la instalación cumpla de forma estricta con estas pautas de seguridad:",
      "- **Circuito exclusivo:** El cableado debe nacer en un interruptor del tablero principal y morir directamente en el cargador. Está prohibido derivar corriente de esa línea para enchufar cualquier otra cosa (salvo iluminación auxiliar del área de carga).\n- **Protecciones individuales:** Cada cargador debe contar con su propio interruptor automático termomagnético (curva C o D según el equipo) y una protección diferencial exclusiva de alta sensibilidad (no mayor a 30 mA) que sea Tipo B o Tipo A combinada con detección de fugas en corriente continua.\n- **Puesta a tierra obligatoria:** El circuito debe incluir un conductor de protección aislado (cable verde-amarillo) conectado firmemente a una toma de tierra que garantice la actuación instantánea de las protecciones en caso de una falla.\n- **Prohibido el uso de prolongadores:** La conexión entre el punto de carga y el auto debe hacerse exclusivamente mediante el cable flexible diseñado para tal fin. Está terminantemente prohibido usar adaptadores o alargues domésticos.",
      "---",
      "<a id=\"conclusion\"></a>",
      "## Conclusión",
      "Instalar un cargador es una inversión que valoriza tu propiedad y garantiza la vida útil de las baterías de tu coche. Para que el proyecto sea exitoso, seguro y no te lleves sorpresas con el suministro de tu casa, el primer paso siempre debe ser un relevamiento técnico profesional que evalúe tu tablero y tu capacidad contratada actual."
    ],
    "featured": true
  },
  {
    "id": "aumento-de-potencia-ute",
    "title": "Aumento de potencia eléctrica en UTE: qué tener en cuenta",
    "date": "09/03/2026",
    "excerpt": "Todo lo que conviene revisar antes de solicitar un aumento de potencia eléctrica en UTE para hogares y comercios.",
    "body": [
      "# Aumento de potencia eléctrica en UTE: qué tener en cuenta",
      "Cuando una vivienda o comercio comienza a incorporar más equipos eléctricos, muchas veces aparece la necesidad de aumentar la potencia contratada en UTE.",
      "Esto puede ocurrir por:",
      "- instalación de aires acondicionados\n- hornos eléctricos\n- termotanques\n- cargadores para vehículos eléctricos\n- talleres\n- bombas\n- ampliaciones de vivienda\n- sistemas de climatización de piscinas",
      "Antes de iniciar el trámite conviene entender algunos aspectos técnicos y administrativos importantes.",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## 📌 Contenido",
      "- [¿Qué significa aumentar la potencia eléctrica?](#que-significa-aumentar-la-potencia-electrica)\n- [Señales de potencia insuficiente](#senales-de-potencia-insuficiente)\n- [Consideraciones](#consideraciones)\n- [Punto de medida](#punto-de-medida)\n- [Tipos de puntos de medida según servicio](#tipos-de-puntos-de-medida-segun-servicio)\n- [Provisorio de obra](#provisorio-de-obra)\n- [Servicio definitivo](#servicio-definitivo)\n- [Propiedades con varios vecinos](#propiedades-con-varios-vecinos)\n- [Qué revisa UTE cuando cambia el medidor](#que-revisa-ute-cuando-cambia-el-medidor)\n- [Casas con medidores antiguos](#casas-con-medidores-antiguos)\n- [Carga de autos eléctricos](#carga-de-autos-electricos)\n- [Documentación](#documentacion)\n- [Costos](#costos)\n- [Recomendaciones](#recomendaciones)\n- [Conclusión](#conclusion)",
      "---",
      "<a id=\"que-significa-aumentar-la-potencia-electrica\"></a>",
      "## ¿Qué significa aumentar la potencia eléctrica?",
      "Es el trámite que se realiza ante UTE, de forma telefónica, remota mediante internet o presencial, en los casos en que se solicitan hasta 7,4 kW.",
      "Para potencias mayores a 7,4 kW, el trámite ya no puede hacerlo directamente el usuario y normalmente requiere intervención de técnico o firma instaladora autorizada.",
      "La potencia contratada define la cantidad máxima de energía que una instalación puede consumir simultáneamente.",
      "Cuando el consumo supera ese límite pueden ocurrir:",
      "- disparo de la térmica ICP\n- cortes reiterados\n- limitaciones al usar varios equipos simultáneamente",
      "Entonces, aumentar potencia permite utilizar más equipos al mismo tiempo cuando el consumo de la vivienda o comercio comienza a crecer.",
      "---",
      "### También te puede interesar",
      "- [¿Qué potencia contratar en UTE para tu casa?](/blog/post/2020/que-potencia-contratar-en-ute-para-tu-casa/)\n- [Requisitos del punto de medida según normativa de UTE](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute)",
      "---",
      "<a id=\"senales-de-potencia-insuficiente\"></a>",
      "## Señales de potencia insuficiente",
      "Algunas señales típicas:",
      "- térmica debajo del medidor de UTE que salta frecuentemente\n- imposibilidad de usar varios equipos simultáneamente\n- cortes al prender calefacción, horno, termotanques o climatización\n- disparo de protecciones cuando aumenta mucho el consumo",
      "---",
      "<a id=\"consideraciones\"></a>",
      "## Consideraciones",
      "Al momento de proyectar un aumento de potencia es donde muchas veces el usuario se lleva una sorpresa.",
      "Esto ocurre porque muchas personas piensan que solamente se trata de pedir el trámite, pero en muchos casos la instalación debe actualizarse para cumplir normativa.",
      "---",
      "<a id=\"punto-de-medida\"></a>",
      "## Punto de medida",
      "Es la instalación que une el cableado de UTE con la instalación interior de la vivienda.",
      "Ahí se encuentra:",
      "- medidor\n- ICP\n- gabinete\n- caños y canalizaciones",
      "En muchos casos el punto de medida debe estar según [normativa vigente de UTE](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute).",
      "---",
      "<a id=\"tipos-de-puntos-de-medida-segun-servicio\"></a>",
      "## Tipos de puntos de medida según servicio",
      "Existen distintos escenarios dependiendo del tipo de servicio que tenga la propiedad.",
      "---",
      "<a id=\"provisorio-de-obra\"></a>",
      "### Provisorio de obra",
      "Este es el servicio que normalmente se solicita para construir una vivienda.",
      "UTE lo otorga de forma temporal y generalmente no permite realizar aumentos de potencia importantes.",
      "Para pasar a servicio definitivo normalmente el punto de medida debe [estar según normativa](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute).",
      "También es necesario:",
      "- no tener deudas con UTE\n- regularizar observaciones\n- actualizar instalaciones antiguas cuando corresponda",
      "---",
      "<a id=\"servicio-definitivo\"></a>",
      "### Servicio definitivo",
      "Es el servicio permanente de una vivienda o comercio.",
      "Permite realizar trámites como:",
      "- aumento de potencia\n- reducción\n- cambio de tarifa\n- regularizaciones",
      "siempre que se cumplan los [requisitos para iniciar trámites ante UTE](/blog/post/2020/trámites-ante-ute-lo-que-debes-saber).",
      "En viviendas antiguas muchas veces UTE exige inspección técnica y actualización parcial de la instalación.",
      "---",
      "<a id=\"propiedades-con-varios-vecinos\"></a>",
      "### Propiedades con varios vecinos",
      "Este es uno de los escenarios más comunes.",
      "Cuando existen varias viviendas dentro del mismo padrón, muchas veces el punto de medida debe modificarse para cumplir normativa y permitir nuevos trámites.",
      "Aunque el usuario no tenga que asumir costos de otros vecinos, igualmente suelen existir gastos importantes de adecuación.",
      "---",
      "<a id=\"que-revisa-ute-cuando-cambia-el-medidor\"></a>",
      "## Qué revisa UTE cuando cambia el medidor",
      "Algunas verificaciones habituales:",
      "- inspección visual general\n- estado del tablero\n- sección de conductores\n- puesta a tierra\n- accesibilidad del medidor\n- cumplimiento general de normativa",
      "---",
      "<a id=\"casas-con-medidores-antiguos\"></a>",
      "## Casas con medidores antiguos",
      "Muchas viviendas antiguas no fueron diseñadas para consumos modernos.",
      "Cuando se pretende aumentar mucho la carga eléctrica, muchas veces se vuelve necesario actualizar:",
      "- línea general\n- tablero\n- protecciones\n- cableado",
      "En estos casos normalmente interviene técnico o firma instaladora autorizada.",
      "---",
      "<a id=\"carga-de-autos-electricos\"></a>",
      "## Carga de autos eléctricos",
      "Una de las causas más comunes de aumento de potencia en Uruguay actualmente es la incorporación de vehículos eléctricos.",
      "Incluso la carga lenta puede generar problemas en viviendas con potencias bajas si funcionan simultáneamente:",
      "- calefón\n- horno\n- aire acondicionado\n- climatización",
      "---",
      "<a id=\"documentacion\"></a>",
      "## Documentación",
      "Dependiendo del caso, normalmente puede requerirse:",
      "- documentación del titular\n- número de cuenta\n- intervención de técnico autorizado\n- regularización del punto de medida",
      "---",
      "<a id=\"costos\"></a>",
      "## Costos",
      "Los costos dependen mucho del estado de la instalación.",
      "En muchos casos el gasto principal no es el trámite de UTE sino:",
      "- adecuación del punto de medida\n- materiales\n- mano de obra\n- actualización de instalación",
      "---",
      "<a id=\"recomendaciones\"></a>",
      "## Recomendaciones",
      "Antes de solicitar un aumento conviene:",
      "- revisar el estado general de la instalación\n- verificar si el punto de medida cumple normativa\n- consultar con técnico autorizado en instalaciones antiguas\n- evaluar realmente cuánto consumo adicional se necesita",
      "---",
      "<a id=\"conclusion\"></a>",
      "## Conclusión",
      "El aumento de potencia eléctrica puede ser un trámite simple en algunos casos y un proceso bastante más complejo en otros.",
      "Cuando existen instalaciones antiguas, servicios provisorios o puntos de medida fuera de normativa, normalmente es necesario realizar adecuaciones antes de que UTE apruebe el trámite."
    ]
  },
  {
    "id": "firma-de-ute-2",
    "title": "Firmas instaldoras UTE nuevas caterogías 2 respuesta de URSEA",
    "date": "12/09/2025",
    "excerpt": "Qué respondió URSEA a las críticas sobre renovaciones, pérdida de categorías, DAR mínimos y restricciones para técnicos autorizados por UTE.",
    "body": [
      "## Resumen",
      "Luego de publicar la nueva propuesta de categorías para instaladores eléctricos autorizados, URSEA recibió decenas de críticas y observaciones por parte de técnicos, estudiantes e instaladores eléctricos de todo Uruguay.",
      "El organismo respondió oficialmente a cada planteo dentro del documento de la Consulta Pública N° 67.",
      "Las respuestas permiten entender mejor:",
      "- Qué aspectos piensa mantener URSEA\n- Qué cosas podrían modificarse\n- Cómo justifican las renovaciones periódicas\n- Qué ocurre con los técnicos actuales\n- Por qué se excluyen ciertas instalaciones\n- Cómo se aplicaría la transición entre categorías",
      "En este artículo resumo los puntos más importantes de esas respuestas oficiales.",
      "---",
      "## 📌 Menú de navegación",
      "- [Qué cuestionaron los técnicos](#que-cuestionaron-los-tecnicos)\n- [La principal crítica: renovación mediante DAR](#la-principal-critica-renovacion-mediante-dar)\n- [Qué respondió URSEA sobre perder la categoría](#que-respondio-ursea-sobre-perder-la-categoria)\n- [Por qué se excluyen ciertas instalaciones](#por-que-se-excluyen-ciertas-instalaciones)\n- [Locales de pública concurrencia y hospitales](#locales-de-publica-concurrencia-y-hospitales)\n- [El problema de los derechos adquiridos](#el-problema-de-los-derechos-adquiridos)\n- [Qué pasa con los técnicos actuales](#que-pasa-con-los-tecnicos-actuales)\n- [Qué opinó URSEA sobre estudiantes avanzados](#que-opino-ursea-sobre-estudiantes-avanzados)\n- [Las inspecciones aleatorias propuestas por técnicos](#las-inspecciones-aleatorias-propuestas-por-tecnicos)\n- [Por qué URSEA insiste con las renovaciones](#por-que-ursea-insiste-con-las-renovaciones)\n- [La diferencia entre título y habilitación UTE](#la-diferencia-entre-titulo-y-habilitacion-ute)\n- [Conclusión](#conclusion)",
      "---",
      "## Qué cuestionaron los técnicos",
      "La enorme mayoría de las contribuciones recibidas durante la consulta pública giraron sobre algunos temas repetidos:",
      "- Cantidad mínima de DAR para renovar\n- Posible pérdida de categoría\n- Restricciones para categoría 1 y 2\n- Exclusión de instalaciones especiales\n- Reducción del campo laboral\n- Derechos adquiridos\n- Situación de estudiantes que estaban terminando carreras\n- Diferencias entre categorías actuales y nuevas",
      "Muchos técnicos consideraron que la propuesta:",
      "- Reduce posibilidades laborales\n- Genera desigualdad entre categorías\n- Favorece a grandes empresas\n- Desconoce cómo funciona realmente el oficio",
      "---",
      "## La principal crítica: renovación mediante DAR",
      "Sin dudas el punto más cuestionado fue la renovación periódica vinculada a la cantidad de instalaciones realizadas.",
      "Muchos técnicos señalaron que:",
      "- Hay electricistas que trabajan en mantenimiento industrial\n- Otros hacen asesoramiento o automatización\n- Algunos trabajan bajo empresas donde no firman DAR personalmente\n- No todos los trabajos implican trámites ante UTE",
      "Varios instaladores afirmaron que usar únicamente los DAR como referencia no refleja realmente la experiencia técnica del profesional.",
      "---",
      "<a href=\"https://www.jorge-electricidad.net/blog/post/2020/firmas-de-ute/\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista autorizado en Maldonado\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## Qué respondió URSEA sobre perder la categoría",
      "URSEA defendió la renovación periódica argumentando que:",
      "- El sector eléctrico cambia rápidamente\n- Existen nuevas tecnologías\n- Se necesita actualización continua\n- Otros rubros también exigen renovaciones",
      "Sin embargo, aclaró algo importante:",
      "> No necesariamente se perdería la habilitación automáticamente por no llegar al mínimo de DAR.",
      "El documento explica que también podría mantenerse la categoría mediante actualización formativa.",
      "Es decir:",
      "- cursos\n- capacitaciones\n- actualización técnica",
      "podrían utilizarse como alternativa.",
      "---",
      "## Por qué se excluyen ciertas instalaciones",
      "URSEA sostiene que algunas instalaciones requieren conocimientos mucho más específicos aunque tengan baja potencia.",
      "Por ejemplo:",
      "- Hospitales\n- Locales bailables\n- Estaciones de servicio\n- Lugares con riesgo de explosión\n- Sistemas fotovoltaicos\n- Cargadores de vehículos eléctricos\n- Sistemas de acumulación",
      "Según el organismo, estas instalaciones:",
      "- poseen riesgos particulares\n- requieren normativa específica\n- incorporan tecnologías más complejas",
      "y no deberían quedar habilitadas automáticamente para categorías básicas.",
      "---",
      "## Locales de pública concurrencia y hospitales",
      "Uno de los puntos más discutidos fue la exclusión de:",
      "- hospitales\n- escuelas\n- locales de pública concurrencia",
      "para categorías 1 y 2.",
      "Muchos técnicos argumentaron que actualmente ya realizan ese tipo de trabajos.",
      "URSEA respondió que:",
      "- el objetivo es especializar más las categorías\n- las instalaciones no son equivalentes a una vivienda común\n- existe mayor responsabilidad técnica\n- la seguridad pública justifica mayores exigencias",
      "Además señalaron que esas instalaciones representan una minoría frente al total de trabajos eléctricos del país.",
      "---",
      "## El problema de los derechos adquiridos",
      "Muchos técnicos sostuvieron que la propuesta vulnera derechos ya obtenidos.",
      "Especialmente:",
      "- categoría C\n- categoría D\n- técnicos con décadas trabajando",
      "URSEA respondió que la transición intentará respetar los derechos efectivamente ejercidos.",
      "Eso significa que:",
      "- si un técnico ya venía realizando ciertos trabajos\n- y puede acreditarlo",
      "mantendría buena parte de sus alcances actuales.",
      "---",
      "## Qué pasa con los técnicos actuales",
      "El documento aclara algo importante:",
      "Las nuevas exigencias aplicarían principalmente a nuevos técnicos que se registren después de entrar en vigencia el nuevo sistema.",
      "Para técnicos ya habilitados existiría un régimen de transición.",
      "Según URSEA:",
      "- categorías B, C y E prácticamente mantendrían sus alcances\n- algunos categoría A conservarían habilitación superior\n- categoría D tendría más cambios y restricciones",
      "También existirían categorías transitorias.",
      "---",
      "## Qué opinó URSEA sobre estudiantes avanzados",
      "Varios estudiantes protestaron porque comenzaron carreras esperando obtener determinadas categorías y la propuesta cambia las reglas antes de terminar.",
      "URSEA respondió que:",
      "- los planes fueron analizados junto con UTU y otras instituciones\n- las categorías se asignaron según contenidos reales\n- no solamente por tradición histórica",
      "Además aclararon que:",
      "> Si el estudiante se registra antes de entrar en vigencia la nueva normativa, aplicaría el sistema actual.",
      "---",
      "## Las inspecciones aleatorias propuestas por técnicos",
      "Varios participantes propusieron algo distinto:",
      "En lugar de exigir cierta cantidad de DAR, preferían:",
      "- inspecciones aleatorias\n- auditorías técnicas\n- sanciones a instalaciones mal ejecutadas",
      "Incluso algunos plantearon:",
      "- suspensiones temporales\n- pérdida definitiva de habilitación ante reincidencias",
      "URSEA respondió que esos controles podrían ser útiles, pero aclaró que:",
      "- exceden el alcance de esta reglamentación\n- corresponden más al sistema de fiscalización de UTE",
      "---",
      "## Por qué URSEA insiste con las renovaciones",
      "El organismo insiste en que el objetivo no sería “sacar técnicos”, sino asegurar actualización técnica.",
      "El documento menciona especialmente:",
      "- vehículos eléctricos\n- electrónica de potencia\n- generación distribuida\n- acumulación de energía\n- automatización\n- nuevas exigencias normativas",
      "URSEA considera que el oficio cambió mucho respecto a décadas anteriores y que las categorías deberían reflejar eso.",
      "---",
      "## La diferencia entre título y habilitación UTE",
      "Uno de los puntos más importantes que aclara el documento es este:",
      "URSEA diferencia claramente:",
      "- el título técnico\n- la habilitación otorgada por UTE",
      "Según la respuesta oficial:",
      "El técnico nunca pierde su formación académica.",
      "Lo que podría perderse es únicamente la habilitación específica para firmar instalaciones ante UTE.",
      "Por ejemplo, un técnico igualmente podría seguir trabajando en:",
      "- mantenimiento\n- automatización\n- proyectos\n- industria\n- asesoramiento técnico",
      "aunque no mantenga determinada habilitación para presentar DAR.",
      "---",
      "## Conclusión",
      "Las respuestas oficiales de URSEA muestran que el organismo piensa mantener gran parte del espíritu original de la reforma.",
      "Aunque algunas observaciones fueron tomadas en cuenta, el documento deja claro que URSEA considera necesarias:",
      "- las renovaciones periódicas\n- la actualización técnica\n- la especialización por tipo de instalación\n- las restricciones para instalaciones complejas",
      "La discusión sigue abierta y todavía falta una eventual aprobación definitiva por parte del Poder Ejecutivo.",
      "Sin embargo, las respuestas de la Consulta Pública permiten ver con bastante claridad cuál es la dirección que busca tomar el nuevo sistema de habilitaciones eléctricas en Uruguay.",
      "---",
      "[> Basado en la Consulta Pública N° 67 y respuestas oficiales de URSEA sobre la nueva propuesta de calificaciones mínimas de idoneidad para instaladores eléctricos en Uruguay](https://plataformaparticipacionciudadana.gub.uy/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhkWGg2WjJGNE1XVTFkelJyT1habFkzTmxhbU5yY1dock1HOXhkUVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVpKcGJteHBibVU3SUdacGJHVnVZVzFsUFNKU1pYTndkV1Z6ZEdGeklHRWdiR0VnWTI5dWMzVnNkR0VnY0hWaWJHbGpZU0JPSlROR0lEWTNMbkJrWmlJN0lHWnBiR1Z1WVcxbEtqMVZWRVl0T0NjblVtVnpjSFZsYzNSaGN5VXlNR0VsTWpCc1lTVXlNR052Ym5OMWJIUmhKVEl3Y0NWRE15VkNRV0pzYVdOaEpUSXdUaVZETWlWQ01DVXlNRFkzTG5Ca1pnWTdCbFE2RVdOdmJuUmxiblJmZEhsd1pVa2lGR0Z3Y0d4cFkyRjBhVzl1TDNCa1pnWTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMzEtMDUtMjZUMTY6MDk6NTQuMDIxWiIsInB1ciI6ImJsb2Jfa2V5In19--951680d47ff2c2c96f8204aeed8d942fee10c0f0/Respuestas%20a%20la%20consulta%20p%C3%BAblica%20N%C2%B0%2067.pdf)"
    ]
  },
  {
    "id": "firma-de-ute-1",
    "title": "Firmas instaldoras UTE nuevas caterogías 1",
    "date": "11/09/2025",
    "excerpt": "Qué cambia con la nueva propuesta de URSEA y UTE para instaladores eléctricos autorizados en Uruguay.",
    "body": [
      "## Resumen",
      "URSEA publicó una nueva propuesta de calificaciones mínimas de idoneidad para instaladores eléctricos en Uruguay, reformulando las categorías tradicionales del Reglamento de Baja Tensión de UTE.",
      "La iniciativa crea nuevas categorías, redefine los alcances permitidos, establece requisitos mínimos de formación y fija criterios para mantener o renovar las habilitaciones.",
      "Aunque actualmente se trata de una propuesta en consulta pública, el documento deja ver claramente hacia dónde apunta el futuro sistema de habilitación para electricistas autorizados en Uruguay.",
      "> Esta propuesta aún se encuentra en etapa de consulta pública y podría sufrir modificaciones antes de su aprobación definitiva.",
      "---",
      "## 📌 Menú de navegación",
      "- [Qué cambia con la nueva propuesta](#que-cambia-con-la-nueva-propuesta)\n- [Nuevas categorías de instaladores eléctricos](#nuevas-categorias-de-instaladores-electricos)\n- [Categoría 1: qué instalaciones puede firmar](#categoria-1-que-instalaciones-puede-firmar)\n- [Categoría 2: instalaciones industriales medianas](#categoria-2-instalaciones-industriales-medianas)\n- [Categoría 3: instalaciones sin límite de potencia](#categoria-3-instalaciones-sin-limite-de-potencia)\n- [Categoría 4: media tensión hasta 36kV](#categoria-4-media-tension-hasta-36kv)\n- [Categoría 5: alta tensión y sistemas de potencia](#categoria-5-alta-tension-y-sistemas-de-potencia)\n- [Instalaciones especiales excluidas](#instalaciones-especiales-excluidas)\n- [Requisitos de formación por categoría](#requisitos-de-formacion-por-categoria)\n- [Cómo se mantiene la habilitación](#como-se-mantiene-la-habilitacion)\n- [Qué ocurre si no se renueva](#que-ocurre-si-no-se-renueva)\n- [Cambio de categoría](#cambio-de-categoria)\n- [Cómo será la transición desde las categorías actuales](#como-sera-la-transicion-desde-las-categorias-actuales)\n- [Cuándo entrarían en vigencia](#cuando-entrarian-en-vigencia)\n- [Conclusión](#conclusion)",
      "---",
      "## Qué cambia con la nueva propuesta",
      "La propuesta presentada por URSEA y elaborada junto con UTE y distintas instituciones educativas busca sustituir el sistema actual de categorías del Capítulo XXIV del Reglamento de Baja Tensión.",
      "El nuevo esquema:",
      "- Redefine las categorías de instaladores\n- Exige formación mínima específica\n- Diferencia claramente baja, media y alta tensión\n- Introduce renovaciones periódicas\n- Establece mecanismos de actualización técnica\n- Vincula las habilitaciones con experiencia comprobable",
      "Además, incorpora exigencias formativas bastante más detalladas que las actuales.",
      "---",
      "## Nuevas categorías de instaladores eléctricos",
      "La propuesta divide las habilitaciones en cinco categorías principales.",
      "| Categoría | Alcance |\n|---|---|\n| 1 | Baja tensión hasta 400V y hasta 50kW |\n| 2 | Baja tensión hasta 400V y hasta 150kW |\n| 3 | Baja tensión sin límite reglamentario de potencia |\n| 4 | Media tensión hasta 36kV |\n| 5 | Alta tensión mayor a 36kV |",
      "Además se crean categorías transitorias cerradas para el pasaje desde el sistema actual:",
      "- 1E\n- 1D\n- 4E",
      "Estas categorías no admitirían nuevos ingresos.",
      "---",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista autorizado en Maldonado\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## Categoría 1: qué instalaciones puede firmar",
      "La categoría 1 permite realizar instalaciones de baja tensión hasta 400V con una potencia contratada de hasta 50kW.",
      "Quedan excluidas instalaciones especiales como:",
      "- Hospitales\n- Locales con riesgo de explosión\n- Locales de pública concurrencia\n- Sistemas de acumulación\n- Carga de vehículos eléctricos\n- Generación eléctrica\n- Instalaciones transitorias",
      "Es una categoría pensada principalmente para:",
      "- Viviendas\n- Pequeños comercios\n- Talleres pequeños",
      "---",
      "## Categoría 2: instalaciones industriales medianas",
      "La categoría 2 amplía el límite hasta 150kW.",
      "Ya incorpora conocimientos vinculados a:",
      "- Instalaciones industriales medianas\n- Calidad de energía\n- Motores eléctricos\n- Automatismos básicos\n- Bancos de condensadores\n- Ensayos y verificaciones",
      "Sin embargo, todavía mantiene restricciones sobre determinadas instalaciones especiales.",
      "---",
      "## Categoría 3: instalaciones sin límite de potencia",
      "La categoría 3 habilita instalaciones de baja tensión sin límite reglamentario de potencia.",
      "Incluye conocimientos avanzados sobre:",
      "- PLC\n- SCADA\n- Variadores de frecuencia\n- Protección contra sobretensiones\n- Calidad de energía\n- Automatización industrial\n- Diseño de instalaciones complejas",
      "Esta categoría ya apunta claramente a instalaciones industriales de gran porte.",
      "---",
      "## Categoría 4: media tensión hasta 36kV",
      "La categoría 4 corresponde a instalaciones de media tensión hasta 36kV.",
      "Exige conocimientos sobre:",
      "- Redes eléctricas\n- Subestaciones\n- Cortocircuitos\n- Protecciones\n- Sistemas de puesta a tierra\n- Operación y mantenimiento de media tensión",
      "Es una categoría claramente orientada a ingeniería eléctrica y sistemas industriales complejos.",
      "---",
      "## Categoría 5: alta tensión y sistemas de potencia",
      "Es la categoría de mayor alcance.",
      "Habilita trabajos en tensiones mayores a 36kV y requiere formación universitaria en sistemas eléctricos de potencia.",
      "Incluye conocimientos sobre:",
      "- Transporte de energía\n- Estabilidad de sistemas eléctricos\n- Redes de alta tensión\n- Protecciones eléctricas avanzadas\n- Generación eléctrica",
      "---",
      "## Instalaciones especiales excluidas",
      "La propuesta define varias instalaciones especiales que quedan restringidas para ciertas categorías.",
      "Entre ellas:",
      "- Hospitales y salas médicas complejas\n- Locales con riesgo de incendio o explosión\n- Locales de pública concurrencia\n- Estaciones de servicio\n- Instalaciones para carga de vehículos eléctricos\n- Sistemas de acumulación de energía\n- Generación eléctrica\n- Instalaciones transitorias para eventos y recitales",
      "Esto marca una tendencia clara hacia una mayor especialización técnica.",
      "---",
      "## Requisitos de formación por categoría",
      "Uno de los cambios más importantes es el aumento de exigencias formativas.",
      "### Categoría 1",
      "Exige:",
      "- 600 horas lectivas mínimas\n- Electrotecnia básica\n- Reglamentación UTE\n- Diseño básico de instalaciones\n- Puesta a tierra\n- Protección eléctrica\n- Proyectos prácticos",
      "### Categoría 2",
      "Exige aproximadamente:",
      "- 900 horas lectivas\n- Cálculos industriales\n- Calidad de energía\n- Automatismos\n- Motores eléctricos\n- Iluminación\n- Ensayos eléctricos",
      "### Categoría 3",
      "Requiere formación terciaria e incorpora:",
      "- PLC\n- SCADA\n- Variadores de frecuencia\n- Mediciones avanzadas\n- Instalaciones industriales complejas\n- Generación para autoconsumo",
      "### Categorías 4 y 5",
      "Ya requieren formación claramente asociada a ingeniería eléctrica.",
      "Especialmente:",
      "- Redes de potencia\n- Media tensión\n- Alta tensión\n- Subestaciones\n- Protecciones\n- Sistemas eléctricos de potencia",
      "---",
      "## Cómo se mantiene la habilitación",
      "La propuesta elimina el concepto de habilitación prácticamente permanente.",
      "Las categorías deberán renovarse periódicamente.",
      "| Categoría | Instalaciones mínimas | Renovación |\n|---|---|---|\n| 1 | 15 instalaciones | Cada 5 años |\n| 2 | 5 instalaciones | Cada 5 años |\n| 3 | 2 instalaciones | Cada 10 años |\n| 4 | 2 instalaciones | Cada 10 años |\n| 5 | 1 instalación | Cada 10 años |",
      "Las instalaciones realizadas se verificarían mediante los DAR presentados ante UTE.",
      "---",
      "## Qué ocurre si no se renueva",
      "Si el instalador no acredita actividad suficiente ni actualización formativa:",
      "- Puede bajar de categoría\n- Puede perder la habilitación\n- Puede quedar suspendido",
      "Por ejemplo:",
      "- Categoría 2 pasaría a categoría 1\n- Categoría 3 pasaría a categoría 2\n- Categoría 1 podría quedar suspendida",
      "Esto introduce un sistema de mantenimiento activo de competencias.",
      "---",
      "## Cambio de categoría",
      "La propuesta permite solicitar una categoría superior en cualquier momento.",
      "Para ello será necesario:",
      "- Acreditar la formación requerida\n- Cumplir los requisitos técnicos correspondientes",
      "Es decir, el ascenso dependería principalmente de la capacitación formal.",
      "---",
      "## Cómo será la transición desde las categorías actuales",
      "El documento también explica cómo pasarían las categorías actuales del Reglamento de Baja Tensión al nuevo sistema.",
      "| Categoría actual | Nueva categoría |\n|---|---|\n| A | 4 o 5 |\n| B | 4E |\n| C | 3 |\n| D | 1 o 1D |\n| E | 1E |",
      "Algunas transiciones dependen de experiencia comprobable en instalaciones específicas.",
      "Por ejemplo:",
      "- Instalaciones de pública concurrencia\n- Trabajos en tensiones mayores a 36kV",
      "---",
      "## Cuándo entrarían en vigencia",
      "La propuesta establece que las nuevas categorías comenzarían a aplicarse un año después de su aprobación por parte del Poder Ejecutivo.",
      "A partir de ese momento:",
      "- Las nuevas habilitaciones se otorgarían bajo el nuevo sistema\n- Las renovaciones también se adaptarían a las nuevas reglas\n- Las categorías anteriores entrarían en transición",
      "---",
      "## Conclusión",
      "La nueva propuesta de URSEA y UTE representa uno de los cambios más importantes en muchos años para los instaladores eléctricos autorizados en Uruguay.",
      "El nuevo modelo apunta a:",
      "- Mayor profesionalización\n- Más formación técnica\n- Diferenciación por complejidad\n- Renovaciones periódicas\n- Mayor control sobre la experiencia práctica",
      "También muestra una tendencia clara hacia la especialización en áreas como:",
      "- Automatización\n- Calidad de energía\n- Vehículos eléctricos\n- Generación distribuida\n- Media y alta tensión",
      "Aunque todavía se trata de una propuesta, es probable que marque el rumbo futuro de las habilitaciones eléctricas en Uruguay.",
      "---"
    ]
  },
  {
    "id": "punto-de-medida-ute",
    "title": "Requisitos del punto de medida según normativa de UTE",
    "date": "11/09/2025",
    "excerpt": "Qué exige UTE para que una instalación de enlace o punto de medida sea aprobada según la normativa vigente.",
    "body": [
      "# Requisitos del punto de medida según normativa de UTE",
      "## Resumen",
      "La instalación de enlace es la parte de la instalación eléctrica que conecta la red de UTE con la instalación interior del cliente. Dentro de ella se encuentra el punto de medida, es decir, el lugar donde se instala el medidor y el ICP.",
      "Muchos trámites ante UTE como aumentos de potencia, nuevos servicios, cambios de medidor o regularizaciones requieren que el punto de medida cumpla con la normativa vigente. Cuando esto no sucede, el trámite puede quedar observado o directamente rechazado.",
      "En este artículo resumimos los principales requisitos establecidos por la Norma de Instalaciones de Enlace de Baja Tensión de UTE vigente.",
      "---",
      "## 📌 Menú de navegación",
      "- [Qué es una instalación de enlace](#que-es-una-instalacion-de-enlace)\n- [Dónde debe ubicarse el medidor](#donde-debe-ubicarse-el-medidor)\n- [Alturas reglamentarias](#alturas-reglamentarias)\n- [Tipos de gabinetes permitidos](#tipos-de-gabinetes-permitidos)\n- [Requisitos del gabinete](#requisitos-del-gabinete)\n- [Instalación desde red aérea](#instalacion-desde-red-aerea)\n- [Instalación desde red subterránea](#instalacion-desde-red-subterranea)\n- [Requisitos del ICP](#requisitos-del-icp)\n- [Canalizaciones y caños](#canalizaciones-y-canos)\n- [Errores comunes observados por UTE](#errores-comunes-observados-por-ute)\n- [Conclusión](#conclusion)",
      "---",
      "## Qué es una instalación de enlace {#que-es-una-instalacion-de-enlace}",
      "Según la normativa de UTE, la instalación de enlace es la que vincula la red de distribución eléctrica de UTE con la instalación interior del cliente.",
      "Está compuesta principalmente por:",
      "- Acometida\n- Gabinete del medidor\n- Medidor\n- ICP (Interruptor de Control de Potencia)\n- Canalizaciones\n- Equipos de comunicación cuando corresponda",
      "El punto de medida es el conjunto donde se aloja el medidor y los elementos asociados necesarios para la medición y control del suministro.",
      "---",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## Dónde debe ubicarse el medidor {#donde-debe-ubicarse-el-medidor}",
      "En suministros individuales con medida directa, el gabinete del medidor debe ubicarse:",
      "- En la línea de propiedad\n- Orientado hacia la vía pública\n- En una posición que permita leer el medidor sin ingresar al predio",
      "UTE además exige que el medidor quede accesible para inspección, mantenimiento y eventual reemplazo.",
      "Puede instalarse:",
      "- En fachada\n- En pilar\n- En reja\n- En columna particular",
      "---",
      "## Alturas reglamentarias",
      "La normativa establece que:",
      "- El visor del medidor debe quedar entre 0,90 m y 1,50 m respecto al suelo\n- El ICP no puede quedar a más de 2,00 m de altura\n- La parte inferior del gabinete del ICP no debe quedar por debajo de 0,30 m",
      "Estas alturas permiten una operación segura y accesible.",
      "---",
      "## Tipos de gabinetes permitidos",
      "UTE exige gabinetes homologados y autorizados.",
      "Los más utilizados son:",
      "| Tipo | Uso |\n|---|---|\n| CM-M | Medidor monofásico |\n| CMI-M | Medidor monofásico + ICP |\n| CM-T | Medidor trifásico |\n| CMI-T | Medidor trifásico + ICP |",
      "El gabinete debe ser apto para medidores inteligentes.",
      "---",
      "## Requisitos del gabinete",
      "El gabinete debe cumplir varias condiciones constructivas:",
      "- Ser de material aislante\n- Ser exclusivo para el medidor o ICP\n- Tener tapa precintable\n- Permitir lectura sin abrir la tapa\n- Tener protección contra humedad\n- Estar firmemente fijado\n- No permitir acceso accidental a partes energizadas",
      "UTE además recomienda evitar exposición solar directa excesiva.",
      "---",
      "## Instalación desde red aérea {#instalacion-desde-red-aerea}",
      "Cuando la alimentación de UTE es aérea, la acometida puede instalarse:",
      "- Aparente\n- Embutida",
      "Los conductos deben:",
      "- Ser rígidos\n- Aislantes\n- No propagadores de llama\n- Resistentes UV\n- Autorizados por URSEA",
      "Además:",
      "- La acometida debe quedar fuera del alcance de la mano\n- La altura mínima de entrada aérea es de 2,50 m\n- Deben evitarse tramos horizontales innecesarios",
      "---",
      "## Instalación desde red subterránea {#instalacion-desde-red-subterranea}",
      "En alimentación subterránea:",
      "- El medidor debe quedar en el límite de propiedad\n- El gabinete debe quedar inmediato a la CGP cuando exista\n- Los conductos deben tener diámetro mínimo reglamentario\n- Debe mantenerse estanqueidad para evitar ingreso de humedad",
      "En instalaciones embutidas normalmente se exigen conductos de reserva.",
      "---",
      "## Requisitos del ICP",
      "El ICP es el interruptor que limita la potencia contratada y protege la instalación.",
      "Puede estar:",
      "- Dentro del mismo gabinete del medidor\n- En gabinete separado",
      "Cuando está separado:",
      "- No puede quedar a más de 15 metros del medidor\n- Debe quedar antes del tablero general interior\n- No puede instalarse en baños ni cocinas",
      "UTE exige además que pueda accionarse sin desmontar tapas ni exponer partes energizadas.",
      "---",
      "## Canalizaciones y caños {#canalizaciones-y-canos}",
      "Las canalizaciones deben ser exclusivas para la instalación de enlace.",
      "No se admite:",
      "- Compartir caños con otros servicios\n- Usar caños deteriorados\n- Conductores expuestos\n- Empalmes improvisados",
      "Los caños y accesorios deben estar autorizados por URSEA.",
      "---",
      "## Errores comunes observados por UTE",
      "Algunas observaciones frecuentes son:",
      "- Medidor instalado dentro de la propiedad\n- Gabinetes no homologados\n- Falta de ICP\n- Caños corrugados expuestos al sol\n- Alturas fuera de norma\n- Conductores visibles o sin protección\n- Rejas o muros que impiden acceso al medidor\n- Instalaciones deterioradas o manipuladas",
      "En muchos aumentos de potencia o regularizaciones, UTE solicita corregir estas situaciones antes de aprobar el trámite.",
      "---",
      "## Conclusión {#conclusion}",
      "La correcta confección del punto de medida no solo es un requisito reglamentario de UTE, sino también una condición fundamental para la seguridad y confiabilidad de la instalación eléctrica.",
      "Realizar la instalación respetando las normas evita observaciones, demoras en trámites y futuras modificaciones costosas.",
      "Ante dudas o modificaciones importantes, siempre es recomendable consultar con un técnico o firma instaladora autorizada."
    ]
  },
  {
    "id": "que-potencia-contratar-en-ute-para-tu-casa",
    "title": "¿Qué potencia contratar en UTE para tu casa?",
    "date": "17/08/2025",
    "excerpt": "Conocé cómo calcular la potencia eléctrica necesaria para tu vivienda y evitar cortes, sobrecargas o problemas con UTE.",
    "body": [
      "# ¿Qué potencia contratar en UTE para una casa?",
      "Elegir correctamente la potencia contratada en UTE es importante para evitar:",
      "- cortes frecuentes\n- disparos de térmicas\n- limitaciones de consumo\n- problemas con equipos de alto consumo",
      "La potencia necesaria depende principalmente de:",
      "- cantidad de electrodomésticos\n- climatización\n- calefacción eléctrica\n- termotanques\n- hornos\n- bombas\n- aire acondicionado\n- hábitos de consumo",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## ¿Cómo calcula UTE la potencia necesaria?",
      "En Uruguay, la potencia sugerida normalmente surge de la evaluación realizada por el técnico actuante según:",
      "- tamaño de la vivienda\n- cantidad de circuitos\n- equipos instalados\n- previsión de consumo simultáneo",
      "No todas las viviendas necesitan la misma potencia contratada.",
      "---",
      "## Diferencia entre monofásico y trifásico",
      "### Monofásico",
      "El suministro monofásico suele utilizarse en viviendas con consumos moderados.",
      "Es habitual en:",
      "- apartamentos\n- casas pequeñas\n- instalaciones básicas",
      "---",
      "### Trifásico",
      "El suministro trifásico se utiliza cuando existen consumos más elevados o equipos específicos.",
      "Por ejemplo:",
      "- bombas importantes\n- talleres\n- motores\n- grandes sistemas de climatización\n- cocinas eléctricas potentes",
      "También puede mejorar el reparto de carga en instalaciones grandes.",
      "---",
      "## Artefactos que más consumen",
      "Algunos equipos que suelen influir mucho en la potencia requerida:",
      "- calefones eléctricos\n- hornos eléctricos\n- aires acondicionados\n- anafes eléctricos\n- secarropas\n- bombas de agua\n- cargadores de vehículos eléctricos",
      "Cuando varios funcionan al mismo tiempo, la demanda aumenta considerablemente.",
      "---",
      "## Señales de que la potencia puede ser insuficiente",
      "Algunas señales frecuentes:",
      "- la térmica se dispara seguido\n- cortes al usar varios equipos simultáneamente\n- caída de tensión\n- luces que bajan de intensidad\n- limitaciones al agregar nuevos equipos",
      "También te puede interesar:",
      "- [Guía rápida para cortes de luz](/blog/post/2020/guia-rapida-cortes-de-luz-)\n- [Señales que precisás un electricista](/blog/post/2020/necesitas-un-electricista)",
      "---",
      "## Normativa UTE y habilitaciones",
      "La principal referencia técnica es la:",
      "> Norma de Instalaciones de Enlace de Baja Tensión",
      "Las instalaciones nuevas o modificaciones importantes normalmente requieren:",
      "- proyecto eléctrico\n- inspección\n- cumplimiento normativo\n- habilitación correspondiente",
      "---",
      "## Tendencias actuales y nuevas exigencias",
      "Las instalaciones modernas incorporan cada vez más:",
      "- medidores inteligentes\n- automatización\n- cargadores para vehículos eléctricos\n- paneles solares\n- monitoreo remoto",
      "Esto puede modificar considerablemente la demanda eléctrica de una vivienda.",
      "También te puede interesar:",
      "- [Domótica en Maldonado: ¿Vale la pena invertir?](/blog/post/2020/domotica-en-maldonado-vale-la-pena-invertir)",
      "---",
      "## Recomendaciones importantes",
      "Antes de aumentar potencia conviene revisar:",
      "- estado de la instalación\n- cableado\n- tablero eléctrico\n- protecciones\n- distribución de cargas",
      "No siempre el problema es solamente la potencia contratada.",
      "---",
      "## Mantenimiento y seguridad",
      "Una instalación eléctrica bien mantenida ayuda a:",
      "- mejorar seguridad\n- evitar sobrecalentamientos\n- reducir fallas\n- proteger electrodomésticos",
      "Siempre es recomendable trabajar con electricistas matriculados y respetar la normativa vigente.",
      "---",
      "## Conclusión",
      "La potencia adecuada depende de las características reales de cada vivienda y del uso eléctrico diario.",
      "Planificar correctamente evita problemas futuros y mejora la seguridad general de la instalación."
    ]
  },
  {
    "id": "necesitas-un-electricista",
    "title": "Señales que precisás un electricista",
    "date": "17/07/2025",
    "excerpt": "Detectá a tiempo los síntomas más comunes de problemas eléctricos antes de que provoquen daños o riesgos de incendio.",
    "body": [
      "## 🚨 Señales de que necesitás un electricista",
      "Algunos problemas eléctricos no solo son molestos: pueden convertirse en riesgos reales para la vivienda y las personas.",
      "Detectar estas señales a tiempo puede evitar:",
      "- incendios\n- daños en electrodomésticos\n- cortocircuitos\n- fugas eléctricas\n- problemas mayores en la instalación",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## ⚠️ 1. Cortes de luz frecuentes en zonas específicas",
      "Si se corta la electricidad solamente en una parte de la casa o las térmicas se disparan constantemente, podría indicar:",
      "- sobrecarga\n- cableado deteriorado\n- conexiones flojas\n- problemas en el tablero eléctrico",
      "También te puede interesar:",
      "- [Guía rápida para cortes de luz](/blog/post/2020/guia-rapida-para-cortes-de-luz/)\n- [¿Qué potencia contratar en UTE para mi casa?](/blog/post/2020/que-potencia-contratar-en-ute-para-mi-casa/)",
      "---",
      "## ⚡ 2. Olor a quemado o plástico derretido",
      "Esta es una de las señales más peligrosas.",
      "Si percibís olor a quemado cerca de:",
      "- enchufes\n- interruptores\n- tableros\n- electrodomésticos",
      "debés cortar la corriente y revisar el problema cuanto antes.",
      "El sobrecalentamiento eléctrico puede provocar incendios.",
      "---",
      "## 🔥 3. Enchufes o llaves calientes",
      "Un enchufe caliente normalmente indica:",
      "- mala conexión\n- exceso de consumo\n- terminal flojo\n- deterioro interno",
      "También puede dañar equipos electrónicos o generar falsos contactos.",
      "👉 Lo recomendable es dejar de usarlo hasta revisarlo.",
      "---",
      "## 💡 4. Luces que titilan o bajan de intensidad",
      "Las luces que parpadean constantemente pueden indicar:",
      "- falsos contactos\n- caída de tensión\n- problemas de neutro\n- conexiones defectuosas",
      "Aunque a veces parezca un problema menor, conviene revisarlo antes de que evolucione a una falla más importante.",
      "---",
      "## 🛑 5. El disyuntor o la térmica se disparan sin motivo claro",
      "Las protecciones eléctricas existen para detectar anomalías.",
      "Si el disyuntor o la térmica saltan repetidamente, normalmente hay:",
      "- sobrecarga\n- fuga eléctrica\n- aparato defectuoso\n- falla de instalación",
      "No conviene seguir rearmando el sistema sin identificar la causa.",
      "---",
      "## 🔌 6. Enchufes flojos, con chispas o quemados",
      "Un enchufe deteriorado puede provocar:",
      "- calentamiento\n- daños en electrodomésticos\n- cortocircuitos\n- riesgo de incendio",
      "Las chispas frecuentes nunca deben considerarse normales.",
      "---",
      "## ⚡ 7. Descargas eléctricas leves",
      "Sentir pequeñas descargas al tocar:",
      "- lavarropas\n- heladeras\n- hornos\n- canillas\n- estructuras metálicas",
      "puede indicar problemas de puesta a tierra o fugas eléctricas.",
      "Esto es especialmente peligroso en ambientes húmedos.",
      "---",
      "## ⚠️ Cuándo pedir asistencia profesional",
      "Conviene contactar a un electricista si detectás:",
      "- olor a quemado\n- enchufes derretidos\n- protecciones que saltan constantemente\n- cables calientes\n- descargas eléctricas\n- cortes frecuentes",
      "La seguridad eléctrica nunca debería dejarse para después.",
      "---",
      "## Conclusión",
      "Muchos problemas eléctricos comienzan con señales pequeñas que suelen ignorarse.",
      "Actuar a tiempo puede evitar daños mayores y mejorar la seguridad del hogar.",
      "Para más información sobre instalaciones eléctricas, mantenimiento y soluciones domiciliarias:"
    ]
  },
  {
    "id": "guia-rapida-cortes-de-luz",
    "title": "Guía rápida para cortes de luz",
    "date": "17/06/2025",
    "excerpt": "Aprendé a detectar las causas más comunes de los cortes de luz domiciliarios y cuándo conviene llamar a un electricista.",
    "body": [
      "## ¿Por qué se corta la luz en mi casa?",
      "Un corte de luz inesperado puede generar molestias, apagar equipos importantes e incluso indicar una falla eléctrica peligrosa.",
      "En esta guía repasamos las causas más comunes de cortes eléctricos domiciliarios y algunas verificaciones básicas que podés realizar antes de llamar a un electricista.",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## 📌 Contenido",
      "- [Sobrecarga del circuito](#1-sobrecarga-del-circuito)\n- [Disyuntor disparado](#2-disyuntor-disparado)\n- [Electrodoméstico con fallas](#3-fallo-en-un-electrodoméstico-específico)\n- [Problemas con el cableado interno](#4-problemas-con-el-cableado-interno)\n- [Problemas externos de UTE](#5-problemas-externos-ute)\n- [Interruptor diferencial disparado](#6-interruptor-diferencial-disparado)\n- [Cuándo llamar a un electricista](#cuándo-llamar-a-un-electricista)\n- [Conclusión](#conclusión)",
      "---",
      "## 1. Sobrecarga del circuito",
      "Cada circuito eléctrico soporta una cantidad limitada de corriente.",
      "Si conectás demasiados aparatos de alto consumo al mismo tiempo, la llave térmica puede dispararse como medida de protección.",
      "### Solución rápida",
      "- Desconectá algunos equipos.\n- Volvé a subir el disyuntor.\n- Verificá si la falla desaparece.",
      "También te puede interesar:",
      "- [¿Qué potencia contratar en UTE para mi casa?](/blog/post/2020/que-potencia-contratar-en-ute-para-tu-casa)",
      "---",
      "## 2. Disyuntor disparado",
      "El disyuntor protege la instalación contra:",
      "- sobrecargas\n- cortocircuitos\n- fallas eléctricas",
      "Cuando se dispara, normalmente indica que detectó un problema en el circuito.",
      "### Solución rápida",
      "- Desconectá todos los equipos del área afectada.\n- Subí nuevamente el disyuntor.\n- Reconectá los aparatos uno por uno.",
      "Si vuelve a dispararse inmediatamente, probablemente exista una falla más importante.",
      "---",
      "## 3. Fallo en un electrodoméstico específico",
      "A veces el problema no está en la instalación eléctrica sino en un aparato defectuoso.",
      "Un electrodoméstico dañado puede generar:",
      "- cortocircuitos\n- fugas\n- sobrecargas\n- disparo del diferencial",
      "### Solución rápida",
      "Si la falla ocurre al conectar un equipo específico:",
      "- desenchufalo\n- verificá si el resto funciona normalmente",
      "También te puede interesar:",
      "- [Reparar un enchufe en casa](/blog/post/2020/como-arreglar-un-enchufe)",
      "---",
      "## 4. Problemas con el cableado interno",
      "Cables deteriorados, conexiones flojas o instalaciones antiguas pueden provocar cortes frecuentes.",
      "Algunas señales de advertencia:",
      "- olor a quemado\n- chispas\n- enchufes calientes\n- luces que parpadean",
      "### Importante",
      "Este tipo de problema requiere revisión profesional.",
      "No conviene manipular instalaciones dañadas sin conocimientos técnicos.",
      "---",
      "## 5. Problemas externos de UTE",
      "A veces el corte no proviene de tu instalación sino de la red eléctrica.",
      "### Verificación rápida",
      "- comprobá si los vecinos tienen suministro\n- revisá avisos de UTE\n- verificá si hay mantenimiento programado",
      "---",
      "## 6. Interruptor diferencial disparado",
      "El interruptor diferencial protege a las personas ante fugas eléctricas.",
      "Puede dispararse por:",
      "- humedad\n- fugas a tierra\n- electrodomésticos defectuosos\n- cableado deteriorado",
      "### Solución rápida",
      "- desconectá todos los equipos\n- subí nuevamente el diferencial\n- reconectá uno por uno",
      "Si se dispara sin nada conectado, probablemente exista una fuga en la instalación.",
      "---",
      "## Cuándo llamar a un electricista",
      "Conviene solicitar asistencia profesional si:",
      "- el problema persiste\n- aparecen chispas\n- hay olor a quemado\n- los disyuntores se disparan constantemente\n- hay cables calientes o derretidos",
      "La seguridad eléctrica siempre debe ser prioridad.",
      "---",
      "## También te puede interesar",
      "- [¿Qué potencia contratar en UTE para mi casa?](/blog/post/2020/que-potencia-contratar-en-ute-para-tu-casa)\n- [Domótica en Maldonado: ¿Vale la pena invertir?](/blog/post/2020/domótica-en-maldonado-vale-la-pena-invertir)",
      "---",
      "## Conclusión",
      "Muchos cortes eléctricos tienen causas simples y fáciles de detectar.",
      "Sin embargo, cuando existen señales de sobrecalentamiento, fugas o fallas repetitivas, lo más seguro es realizar una revisión profesional."
    ]
  },
  {
    "id": "dom-tica-en-maldonado-vale-la-pena-invertir",
    "title": "Domótica en Maldonado: ¿Vale la pena invertir?",
    "date": "17/04/2025",
    "excerpt": "Descubrí cómo la domótica puede mejorar la seguridad, el ahorro energético y el control remoto de tu hogar.",
    "body": [
      "# Domótica en Maldonado: ¿Vale la pena invertir?",
      "## Resumen",
      "La tecnología para el hogar ya no es algo exclusivo de películas futuristas.",
      "En Maldonado y Punta del Este, cada vez más viviendas incorporan sistemas de domótica para automatizar:",
      "- iluminación\n- climatización\n- cámaras de seguridad\n- portones\n- alarmas\n- riego\n- control remoto del hogar",
      "Pero, ¿realmente vale la pena invertir en domótica? Depende del uso de la vivienda y de las necesidades de cada persona.",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## ¿Qué es la domótica?",
      "La domótica consiste en integrar tecnología inteligente en una vivienda para mejorar:",
      "- comodidad\n- seguridad\n- eficiencia energética\n- automatización de tareas",
      "Esto se logra mediante dispositivos conectados que pueden controlarse desde:",
      "- celular\n- tablet\n- asistentes virtuales\n- sensores automáticos\n- rutinas programadas",
      "---",
      "## Beneficios concretos en Maldonado",
      "### Ahorro energético",
      "En viviendas de uso temporal o segundas residencias, la automatización permite:",
      "- apagar luces automáticamente\n- controlar climatización\n- optimizar consumo eléctrico\n- monitorear equipos a distancia",
      "---",
      "### Seguridad",
      "La integración con cámaras, alarmas y sensores permite supervisar la propiedad desde cualquier lugar.",
      "También te puede interesar:",
      "- [Conectividad e integración para cámaras de seguridad](/blog/post/2020/conectividad-e-integracion-para-camaras-de-seguridad/)\n- [Consideraciones de instalación para cámaras de seguridad](/blog/post/2020/consideraciones-de-instalacion-para-camaras-de-seguridad/)",
      "---",
      "### Comodidad y control",
      "La domótica permite automatizar tareas cotidianas como:",
      "- abrir portones\n- controlar luces\n- regular temperatura\n- programar escenas automáticas\n- controlar dispositivos desde el celular",
      "---",
      "### Valor agregado a la propiedad",
      "Las viviendas inteligentes están ganando cada vez más interés en el mercado inmobiliario, especialmente en propiedades modernas o de alquiler temporal.",
      "---",
      "## ¿Es costosa la domótica?",
      "El costo depende mucho del nivel de automatización.",
      "Actualmente existen soluciones escalables que permiten comenzar poco a poco:",
      "- iluminación inteligente\n- control de portones\n- cámaras conectadas\n- sensores\n- automatización parcial",
      "No es necesario automatizar toda la vivienda desde el inicio.",
      "---",
      "## ¿Vale la pena invertir?",
      "Sí, especialmente en viviendas donde se busca:",
      "- mayor seguridad\n- control remoto\n- ahorro energético\n- monitoreo a distancia\n- comodidad diaria",
      "En Maldonado y Punta del Este, donde muchas propiedades permanecen vacías parte del año, la domótica puede aportar beneficios muy concretos.",
      "---",
      "## Recomendaciones antes de instalar domótica",
      "Antes de invertir conviene evaluar:",
      "- calidad de la red Wi-Fi\n- estabilidad eléctrica\n- compatibilidad entre dispositivos\n- posibilidad de futuras ampliaciones\n- soporte técnico disponible",
      "Una mala planificación puede generar sistemas difíciles de mantener o incompatibilidades entre marcas.",
      "---",
      "## También te puede interesar",
      "- [Conectividad e integración para cámaras de seguridad](/blog/post/2020/conectividad-e-integracion-para-camaras-de-seguridad/)\n- [Seguridad informática para cámaras de vigilancia](/blog/post/2020/seguridad-informatica-camaras-vigilancia/)\n- [¿Qué potencia contratar en UTE para mi casa?](/blog/post/2020/que-potencia-contratar-en-ute-para-mi-casa/)",
      "---",
      "## Conclusión",
      "La domótica dejó de ser una tecnología exclusiva o inaccesible.",
      "Hoy existen soluciones adaptables para distintos presupuestos y necesidades, especialmente útiles en hogares modernos y propiedades de uso parcial.",
      "Implementada correctamente, puede mejorar:",
      "- seguridad\n- eficiencia\n- comodidad\n- control remoto\n- valor de la propiedad"
    ]
  },
  {
    "id": "tr-mites-ante-ute-lo-que-debes-saber",
    "title": "Trámites ante UTE lo que debes saber",
    "date": "17/03/2025",
    "excerpt": "Aspectos a tener en cuenta antes de iniciar trámites en UTE.",
    "body": [
      "## Resumen",
      "Iniciar un trámite ante UTE en la mayoría de los casos requiere cumplir requisitos que muchas veces el usuario desconoce y se entera cuando intenta realizarlo,\na continuación analizaremos los distintos casos",
      "## 📌 Menú de navegación",
      "- [Caso 1: Trámite cambio de titular ante UTE](#-caso-1-trámite-cambio-de-titular-ante-ute)\n- [Caso 2: Trámite aumento de potencia en UTE](#caso-2-trámite-aumento-de-pontecia-en-ute)\n- [Caso 3: Trámite solicitud de nuevo servicio en UTE](#caso-3-trámite-solicitud-de-nuevo-servicio-en-ute)\n- [Caso 4: Cambio de lugar del ICP de UTE](#caso-4-cambio-de-lugar-del-icp-de-ute)",
      "### 📍 Caso 1: Trámite cambio de titular ante UTE",
      "- Estar al día con las facturas\n- Tener el servicio definitivo no el provisorio \n- Ser quién va ser el titular en traspasos de cuentas (el titular actual no debe hacer nada)",
      "### Caso 2: Trámite aumento de pontecia en UTE\n \n- Tener el servicio definitivo no provisorio de obra \n- Estar al día con las facturas\n- Aumento por encima de 7 kw el trámite debe hacerlo un técnico o firma instaladora\n- En casas antiguas con medidores que no son inteligentes, el punto de medida , donde está el medidor , [debe estar según normativa](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute)",
      "### Caso 3: Trámite solicitud de nuevo servicio en UTE",
      "- Lo realiza únicamente el técnico o firma instaldora \n- No tener deuda vigente con UTE \n- Pagar la tasa de conexión de UTE por única vez de unos 6000$ aprox \n Documentación\n  - Foto de Cédula\n  - N° de padrón\n  - Datos de lugar actual de residencia\n  - Depósito económico variable, a modo de garantía\n  - Datos de ubicación del padrón\n  - N° de medidor del vecino más cercano\n  \n### Caso 4: Cambio de lugar del ICP de UTE",
      "- Tener servicio definitivo no provisorio de obra\n- Estar al día con las facturas\n- Tener el punto de medida [según normativa](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute)",
      "### Caso 4: Cambio de lugar del medidor",
      "- Tener servicio definitivo no provisorio de obra\n- Estar al día con las facturas\n- Que el nuevo lugar esté [según normativa](/blog/post/2020/requisitos-para-nicho-o--punto-para-medidor-de-ute)"
    ]
  },
  {
    "id": "consideraciones-de-instalaci-n-para-c-maras-de-seguridad-2",
    "title": "Consideraciones de instalación para cámaras de seguridad",
    "date": "17/03/2025",
    "excerpt": "Consejos sobre ubicación, cableado e instalación profesional de cámaras de seguridad para mejorar la cobertura y la seguridad.",
    "body": [
      "# Consideraciones de instalación para cámaras de seguridad",
      "## Resumen",
      "La instalación adecuada de un sistema de videovigilancia es tan importante como la selección de los equipos.",
      "Una planificación correcta y una instalación profesional ayudan a mejorar:",
      "- cobertura\n- estabilidad\n- calidad de grabación\n- durabilidad del sistema",
      "En esta guía repasamos los principales aspectos a tener en cuenta para instalar cámaras de seguridad correctamente en hogares y comercios.",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "## Guía para elegir tu sistema de vigilancia",
      "En el siguiente video podés ver algunos aspectos importantes sobre instalación, cobertura y planificación de cámaras de seguridad.",
      "<div style=\"display:flex; justify-content:center; margin:20px 0;\">\n  <video controls preload=\"metadata\" playsinline\n    poster=\"https://ik.imagekit.io/tnzquipyu/BLOG/poster%20reproducir.png\"\n    style=\"max-width:100%; max-height:700px; border-radius:12px;\">\n    \n  <source src=\"https://ik.imagekit.io/tnzquipyu/BLOG/camaras%20guia.mp4\" type=\"video/mp4\">\n    \n    Tu navegador no soporta video HTML5.\n  </video>\n</div>",
      "---"
    ]
  },
  {
    "id": "como-arreglar-un-enchufe",
    "title": "Reparar un enchufe en casa",
    "date": "17/01/2025",
    "excerpt": "Aprendé cómo revisar y reparar un enchufe dañado de forma segura para evitar riesgos eléctricos en el hogar.",
    "body": [
      "# Reparar un enchufe en casa: Guía completa",
      "Un enchufe flojo, que no funciona o que hace algún tipo de ruido puede parecer un problema menor, pero puede esconder riesgos eléctricos importantes.",
      "En este post te explico **cómo revisar y arreglar un enchufe de pared de forma segura**, paso a paso, usando herramientas básicas y evitando errores comunes.",
      "<a href=\"https://www.jorge-electricidad.net/\" target=\"_blank\">\n  <img src=\"https://ik.imagekit.io/tnzquipyu/jorge-electricidad.png\"\n       alt=\"Electricista en Maldonado y Punta del Este\"\n       style=\"border-radius:12px; margin:20px 0;\">\n</a>",
      "---",
      "## ⚠️ Antes de empezar",
      "> **Cortá la corriente desde el tablero general.**",
      "Nunca trabajes con tensión en un toma corriente y baja la llave de UTE no la del tablero, esto te evitará sorpresas.",
      "---",
      "## También te puede interesar",
      "- [Reparar un enchufe en casa](/blog/post/2020/2020/reparar-un-enchufe-en-casa/)\n- [Guía rápida para cortes de luz](/blog/post/2020/2020/guia-rapida-para-cortes-de-luz/)\n- [¿Qué potencia contratar en UTE para mi casa?](/blog/post/2020/2020/que-potencia-contratar-en-ute-para-mi-casa/)\n---",
      "---",
      "## Herramientas que vas a necesitar",
      "- Destornillador plano o Phillips\n- Tester, buscapolos o lámpara de prueba (deseable)\n- Alicate pelacables (opcional)\n- Toma corriente nuevo (si hay que reemplazarlo)",
      "---",
      "## Video: reparación básica de enchufe",
      "<div style=\"display:flex; justify-content:center; margin:20px 0;\">\n  <video controls preload=\"metadata\" playsinline\n    style=\"max-width:100%; max-height:700px; border-radius:12px;\">\n    <source src=\"https://ik.imagekit.io/tnzquipyu/reparar%20enchufe.mp4\" type=\"video/mp4\">\n    Tu navegador no soporta video HTML5.\n  </video>\n</div>"
    ]
  }
];

/** Admin whitelist (single email allowed). */
export const ADMIN_EMAIL = "sixtamux@gmail.com";
